POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "hm",
  "number": "123"
}

###

POST https://phonebook-backend-fso.fly.dev/api/persons
content-type: application/json

{
  "name": "Jesusalmight",
  "number": "123323"
}