POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Dan King",
  "number": "123"
}

###

POST https://phonebook-backend-fso.fly.dev/api/persons
content-type: application/json

{
  "name": "KKK",
  "number": "123323"
}